apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-shop-db-creds
  namespace: eso-shop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: conjur-store
    kind: ClusterSecretStore
  target:
    name: eso-shop-db-creds
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: data/vault/dev-demo-aslan/dbuser_dual/username
    - secretKey: DB_PASS
      remoteRef:
        key: data/vault/dev-demo-aslan/dbuser_dual/password
    - secretKey: DB_HOST
      remoteRef:
        key: data/vault/dev-demo-aslan/dbuser_dual/address
