apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-shop-sa
  namespace: eso-shop
  annotations:
    # Conjur JWT authenticator reads these claims from the projected token
    conjur.org/authn-jwt-service-id: eks-latam
